// this jobTitles used at recruiter side to find candidate feature
export const jobTitles = [
  // Software & IT
  "Software Engineer",
  "React Developer",
  "Java Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Cybersecurity Analyst",
  "DevOps Engineer",
  "Cloud Engineer",
  "Database Administrator",
  "Blockchain Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Mobile App Developer",

  // Product & Management
  "Product Manager",
  "Project Manager",
  "Business Analyst",
  "Scrum Master",
  "Operations Manager",
  "Risk Manager",
  "Supply Chain Manager",

  // Sales & Marketing
  "Marketing Manager",
  "Sales Executive",
  "Digital Marketing Specialist",
  "SEO Analyst",
  "Social Media Manager",
  "Brand Manager",
  "Public Relations Specialist",

  // HR & Administration
  "Human Resources Manager",
  "Recruiter",
  "Training and Development Manager",
  "Administrative Officer",

  // Finance & Banking
  "Financial Analyst",
  "Investment Banker",
  "Accountant",
  "Auditor",
  "Tax Consultant",
  "Actuary",
  "Loan Officer",

  // Engineering
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Automobile Engineer",
  "Aerospace Engineer",
  "Chemical Engineer",
  "Biomedical Engineer",
  "Structural Engineer",

  // Healthcare & Medicine
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Dentist",
  "Physiotherapist",
  "Radiologist",
  "Veterinarian",
  "Surgeon",

  // Legal & Law
  "Lawyer",
  "Judge",
  "Paralegal",
  "Legal Advisor",

  // Education & Research
  "Teacher",
  "Professor",
  "Research Scientist",
  "Librarian",
  "Academic Counselor",

  // Creative & Media
  "Graphic Designer",
  "UI/UX Designer",
  "Content Writer",
  "Journalist",
  "Video Editor",
  "Animator",
  "Art Director",
  "Photographer",
  "Filmmaker",
  "Fashion Designer",
  "Interior Designer",
  "Music Producer",

  // Hospitality & Tourism
  "Hotel Manager",
  "Event Planner",
  "Chef",
  "Tour Guide",
  "Travel Agent",
  "Flight Attendant",

  // Sports & Fitness
  "Athlete",
  "Fitness Trainer",
  "Sports Coach",
  "Physiotherapist",

  // Government & Public Sector
  "Police Officer",
  "Firefighter",
  "Military Officer",
  "Social Worker",
  "Diplomat",

  // Miscellaneous
  "Entrepreneur",
  "Freelancer",
  "Data Entry Operator",
  "Customer Support Representative",
];

// these location use to in home page to find job
export const allLocations = {
  "Andhra Pradesh": [
    "Visakhapatnam, Andhra Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Guntur, Andhra Pradesh",
  ],
  "Arunachal Pradesh": [
    "Itanagar, Arunachal Pradesh",
    "Tawang, Arunachal Pradesh",
    "Pasighat, Arunachal Pradesh",
  ],
  Assam: ["Guwahati, Assam", "Silchar, Assam", "Dibrugarh, Assam"],
  Bihar: ["Patna, Bihar", "Gaya, Bihar", "Bhagalpur, Bihar"],
  Chhattisgarh: [
    "Raipur, Chhattisgarh",
    "Bilaspur, Chhattisgarh",
    "Durg, Chhattisgarh",
  ],
  Delhi: ["New Delhi, Delhi", "Rohini, Delhi", "Dwarka, Delhi"],
  Goa: ["Panaji, Goa", "Margao, Goa", "Vasco da Gama, Goa"],
  Gujarat: ["Ahmedabad, Gujarat", "Surat, Gujarat", "Vadodara, Gujarat"],
  Haryana: ["Gurugram, Haryana", "Faridabad, Haryana", "Karnal, Haryana"],
  "Himachal Pradesh": [
    "Shimla, Himachal Pradesh",
    "Manali, Himachal Pradesh",
    "Dharamshala, Himachal Pradesh",
  ],
  Jharkhand: [
    "Ranchi, Jharkhand",
    "Jamshedpur, Jharkhand",
    "Dhanbad, Jharkhand",
  ],
  "Jammu and Kashmir": [
    "Srinagar, Jammu and Kashmir",
    "Jammu, Jammu and Kashmir",
    "Anantnag, Jammu and Kashmir",
  ],
  Karnataka: [
    "Bengaluru, Karnataka",
    "Mysuru, Karnataka",
    "Hubli, Karnataka",
  ],
  Kerala: [
    "Thiruvananthapuram, Kerala",
    "Kochi, Kerala",
    "Kozhikode, Kerala",
  ],
  Ladakh: ["Leh, Ladakh", "Kargil, Ladakh"],
  "Madhya Pradesh": [
    "Bhopal, Madhya Pradesh",
    "Indore, Madhya Pradesh",
    "Gwalior, Madhya Pradesh",
  ],
  Maharashtra: [
    "Mumbai, Maharashtra",
    "Pune, Maharashtra",
    "Nagpur, Maharashtra",
  ],
  Manipur: ["Imphal, Manipur", "Bishnupur, Manipur", "Thoubal, Manipur"],
  Meghalaya: ["Shillong, Meghalaya", "Tura, Meghalaya", "Jowai, Meghalaya"],
  Mizoram: ["Aizawl, Mizoram", "Lunglei, Mizoram", "Champhai, Mizoram"],
  Nagaland: ["Kohima, Nagaland", "Dimapur, Nagaland", "Mokokchung, Nagaland"],
  Odisha: ["Bhubaneswar, Odisha", "Cuttack, Odisha", "Rourkela, Odisha"],
  Punjab: ["Ludhiana, Punjab", "Amritsar, Punjab", "Jalandhar, Punjab"],
  Rajasthan: ["Alwar, Rajasthan", "Jaipur, Rajasthan", "Udaipur, Rajasthan"],
  Sikkim: ["Gangtok, Sikkim", "Namchi, Sikkim", "Gyalshing, Sikkim"],
  "Tamil Nadu": [
    "Chennai, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Madurai, Tamil Nadu",
  ],
  Telangana: [
"Adilabad, Telangana",  
"Adilabad Rural, Telangana",  
"Adilabad Urban, Telangana",  
"Bazarhatnoor, Telangana",  
"Bela, Telangana",  
"Bheempur, Telangana",  
"Boath, Telangana",  
"Gadiguda, Telangana",  
"Gudihatnoor, Telangana",  
"Ichoda, Telangana",  
"Inderavelly, Telangana",  
"Jainath, Telangana",  
"Mavala, Telangana",  
"Narnoor, Telangana",  
"Neradigonda, Telangana",  
"Sirikonda, Telangana",  
"Talamadugu, Telangana",  
"Tamsi, Telangana",  
"Utnoor, Telangana",  

"Bhadradri Kothagudem, Telangana",  
"Allapalli, Telangana",  
"Annapureddypalli, Telangana",  
"Aswapuram, Telangana",  
"Aswaraopeta, Telangana",  
"Bhadrachalam, Telangana",  
"Burgampahad, Telangana",  
"Chandrugonda, Telangana",  
"Cherla, Telangana",  
"Chunchupalli, Telangana",  
"Dammapeta, Telangana",  
"Dummugudem, Telangana",  
"Gundala, Telangana",  
"Julurupadu, Telangana",  
"Karakagudem, Telangana",  
"Kothagudem, Telangana",  
"Laxmidevipalli, Telangana",  
"Manugur, Telangana",  
"Mulakalapally, Telangana",  
"Palwancha, Telangana",  
"Pinapaka, Telangana",  
"Sujathanagar, Telangana",  
"Tekulapally, Telangana",  
"Yellandu, Telangana",  

"Hanumakonda, Telangana",  
"Atmakur, Telangana",  
"Bheemadevarapalli, Telangana",  
"Damera, Telangana",  
"Dharmasagar, Telangana",  
"Elkathurthi, Telangana",  
"Hanamkonda, Telangana",  
"Hasanparthy, Telangana",  
"Inavole, Telangana",  
"Kamalapur, Telangana",  
"Khazipet, Telangana",  
"Nadikuda, Telangana",  
"Parkal, Telangana",  
"Shayampet, Telangana",  
"Velair, Telangana",  

"Amberpet, Hyderabad",  
"Ameerpet, Hyderabad",  
"Asifnagar, Hyderabad",  
"Bahadurpura, Hyderabad",  
"Bandlaguda, Hyderabad",  
"Charminar, Hyderabad",  
"Golconda, Hyderabad",  
"Himayathnagar, Hyderabad",  
"Khairthabad, Hyderabad",  
"Marredpally, Hyderabad",  
"Musheerabad, Hyderabad",  
"Nampally, Hyderabad",  
"Saidabad, Hyderabad",  
"Secunderabad, Hyderabad",  
"Shaikpet, Hyderabad",  
"Tirumalgiri, Hyderabad",  
"Tirumalagiry, Hyderabad",

"Jagitial, Telangana",  
"Beerpur, Telangana",  
"Buggaram, Telangana",  
"Dharmapuri, Telangana",  
"Gollapalli, Telangana",  
"Ibrahimpatnam, Telangana",  
"Jagitial Rural, Telangana",  
"Jagtial, Telangana",  
"Kathalapur, Telangana",  
"Kodimial, Telangana",  
"Korutla, Telangana",  
"Mallapur, Telangana",  
"Mallial, Telangana",  
"Medipalli, Telangana",  
"Metpalli, Telangana",  
"Pegadapalli, Telangana",  
"Raikal, Telangana",  
"Sarangapur, Telangana",  
"Velgatoor, Telangana",  

"Jangoan, Telangana",  
"Bachannapeta, Telangana",  
"Chilpur, Telangana",  
"Devaruppula, Telangana",  
"Ghanpur (Station), Telangana",  
"Jangaon, Telangana",  
"Kodakandla, Telangana",  
"Lingalaghanpur, Telangana",  
"Narmetta, Telangana",  
"Palakurthi, Telangana",  
"Raghunathpalle, Telangana",  
"Tharigoppula, Telangana",  
"Zaffergadh, Telangana",  

"Jayashankar Bhupalapally, Telangana",  
"Bhupalpalle, Telangana",  
"Chityal, Telangana",  
"Ghanapur (Mulug), Telangana",  
"Kataram, Telangana",  
"Mahadevpur, Telangana",  
"Malhar Rao, Telangana",  
"Mogullapalle, Telangana",  
"Mutharam (Mahadevpur), Telangana",  
"Palimela, Telangana",  
"Regonda, Telangana",  
"Tekumatla, Telangana",  

"Jogulamba Gadwal, Telangana",  
"Alampur, Telangana",  
"Dharur, Telangana",  
"Gadwal, Telangana",  
"Ghattu, Telangana",  
"Ieeja, Telangana",  
"Itikyal, Telangana",  
"Kaloor Thimmandoddi, Telangana",  
"Maldakal, Telangana",  
"Manopadu, Telangana",  
"Rajoli, Telangana",  
"Undavelly, Telangana",  
"Waddepalle, Telangana",  
"Waddepally, Telangana",  

"Kamareddy, Telangana",  
"Banswada, Telangana",  
"Bhiknur, Telangana",  
"Bibipet, Telangana",  
"Bichkunda, Telangana",  
"Birkoor, Telangana",  
"Domakonda, Telangana",  
"Gandhari, Telangana",  
"Jukkal, Telangana",  
"Kamareddy, Telangana",  
"Lingampet, Telangana",  
"Machareddy, Telangana",  
"Madnur, Telangana",  
"Nagireddypet, Telangana",  
"Nasurullabad, Telangana",  
"Nizamsagar, Telangana",  
"Pedda Kodapgal, Telangana",  
"Pitlam, Telangana",  
"Rajampet, Telangana",  
"Ramareddy, Telangana",  
"Sadasivanagar, Telangana",  
"Tadwai, Telangana",  
"Yellareddy, Telangana",  

"Karimnagar, Telangana",  
"Chigurumamidi, Telangana",  
"Choppadandi, Telangana",  
"Ellandakunta, Telangana",  
"Gangadhara, Telangana",  
"Ganneruvaram, Telangana",  
"Huzurabad, Telangana",  
"Jammikunta, Telangana",  
"Karimnagar, Telangana",  
"Karimnagar Rural, Telangana",  
"Kothapally, Telangana",  
"Manakondur, Telangana",  
"Ramadugu, Telangana",  
"Shankarapatnam, Telangana",  
"Thimmapur LMD, Telangana",  
"V. Saidapur, Telangana",  
"Veenavanka, Telangana",  

"Khammam, Telangana",  
"Bonakal, Telangana",  
"Chinthakani, Telangana",  
"Enkoor, Telangana",  
"Kalluru, Telangana",  
"Kallur, Telangana",  
"Kamepalli, Telangana",  
"Kamepally, Telangana",  
"Khammam (Rural), Telangana",  
"Khammam (Urban), Telangana",  
"Konijerla, Telangana",  
"Kusumanchi, Telangana",  
"Madhira, Telangana",  
"Mudigonda, Telangana",  
"Nelakondapalli, Telangana",  
"Nelakondapally, Telangana",  
"Penuballi, Telangana",  
"Penubally, Telangana",  
"Raghunadhapalem, Telangana",  
"Sathupalli, Telangana",  
"Sathupally, Telangana",  
"Singareni, Telangana",  
"Thallada, Telangana",  
"Tirumalayapalem, Telangana",  
"Thirumalayapalem, Telangana",  
"Vemsoor, Telangana",  
"Wyra, Telangana",  
"Yerrupalem, Telangana",  

"Kumuram Bheem Asifabad, Telangana",  
"Asifabad, Telangana",  
"Bejjur, Telangana",  
"Chintalamanepally, Telangana",  
"Dahegaon, Telangana",  
"Jainoor, Telangana",  
"Kagaznagar, Telangana",  
"Kerameri, Telangana",  
"Kouthala, Telangana",  
"Lingapur, Telangana",  
"Penchicalpet, Telangana",  
"Rebbena, Telangana",  
"Sirpur (T), Telangana",  
"Sirpur (U), Telangana",  
"Tiryani, Telangana",  
"Wankidi, Telangana",  

"Mahabubabad, Telangana",  
"Bayyaram, Telangana",  
"Chinnagudur, Telangana",  
"Danthalapalle, Telangana",  
"Dornakal, Telangana",  
"Gangaram, Telangana",  
"Garla, Telangana",  
"Gudur, Telangana",  
"Kesamudram, Telangana",  
"Kothagudem, Telangana",  
"Kuravi, Telangana",  
"Mahbubabad, Telangana",  
"Maripeda, Telangana",  
"Nallikudur, Telangana",  
"Narsimhulapet, Telangana",  
"Peddavangara, Telangana",  
"Thorrur, Telangana",  

"Mahabubnagar, Telangana",  
"Addakal, Telangana",  
"Balanagar, Telangana",  
"Bhoothpur, Telangana",  
"Chinnachintakunta, Telangana",  
"Devarakadara, Telangana",  
"Gandeed, Telangana",  
"Hanwada, Telangana",  
"Jadcherla, Telangana",  
"Koilkonda, Telangana",  
"Mahabubnagar Urban, Telangana",  
"Mahbubnagar Rural, Telangana",  
"Midjil, Telangana",  
"Mohammadabad, Telangana",  
"Moosapet, Telangana",  
"Nawabpet, Telangana",  
"Rajapur, Telangana",  

"Mancherial, Telangana",  
"Bellampally, Telangana",  
"Bheemaram, Telangana",  
"Bheemini, Telangana",  
"Chennur, Telangana",  
"Dandepally, Telangana",  
"Hajipur, Telangana",  
"Jaipur, Telangana",  
"Jannaram, Telangana",  
"Kannepally, Telangana",  
"Kasipet, Telangana",  
"Kotapally, Telangana",  
"Luxettipet, Telangana",  
"Mancherial, Telangana",  
"Mandamarri, Telangana",  
"Naspur, Telangana",  
"Nennel, Telangana",  
"Tandur, Telangana",  
"Vemanpally, Telangana",  

"Medak, Telangana",  
"Alladurg, Telangana",  
"Chegunta, Telangana",  
"Chilpched, Telangana",  
"Havelighanapur, Telangana",  
"Kowdipalli, Telangana",  
"Kulcharam, Telangana",  
"Manoharabad, Telangana",  
"Masaipet, Telangana",  
"Medak, Telangana",  
"Narsapur, Telangana",  
"Narsingi, Telangana",  
"Nizampet, Telangana",  
"Papannapet, Telangana",  
"Ramayampet, Telangana",  
"Regode, Telangana",  
"Shankarampet [A], Telangana",  
"Shankarampet [R], Telangana",  
"Shivampet, Telangana",  
"Tekmal, Telangana",  
"Tupran, Telangana",  
"Yeldurthy, Telangana",    

"Medchal Malkajgiri, Telangana",  
"Alwal, Telangana",  
"Bachupally, Telangana",  
"Balanagar, Telangana",  
"Dundigal Gandimaisamma, Telangana",  
"Gandimaisamma Dundigal, Telangana",  
"Ghatkesar, Telangana",  
"Kapra, Telangana",  
"Keesara, Telangana",  
"Kukatpally, Telangana",  
"Malkajgiri, Telangana",  
"Medchal, Telangana",  
"Medipally, Telangana",  
"Muduchinthalapally, Telangana",  
"Quthbullapur, Telangana",  
"Qutballapur, Telangana",  
"Shamirpet, Telangana",  
"Uppal, Telangana",  

"Mulugu, Telangana",  
"Eturnagaram, Telangana",  
"Govindaraopet, Telangana",  
"Kannaigudem, Telangana",  
"Mangapet, Telangana",  
"Mulug, Telangana",  
"Tadvai, Telangana",  
"Venkatapur, Telangana",  
"Venkatapuram, Telangana",  
"Wajedu, Telangana",  
"Wazeed, Telangana",  

"Nagarkurnool, Telangana",  
"Achampeta, Telangana",  
"Amrabad, Telangana",  
"Balmoor, Telangana",  
"Bijinapalle, Telangana",  
"Charakonda, Telangana",  
"Kalwakurthy, Telangana",  
"Kodair, Telangana",  
"Kollapur, Telangana",  
"Lingal, Telangana",  
"Nagarkurnool, Telangana",  
"Padara, Telangana",  
"Peddakothapalle, Telangana",  
"Pentlavelli, Telangana",  
"Tadoor, Telangana",  
"Telkapalle, Telangana",  
"Thimmajipeta, Telangana",  
"Uppununthala, Telangana",  
"Urkonda, Telangana",  
"Vangoor, Telangana",  
"Veldanda, Telangana",  

"Nalgonda, Telangana",  
"Adavidevulapalli, Telangana",  
"Anumula, Telangana",  
"Chandampet, Telangana",  
"Chandur, Telangana",  
"Chintha Pally, Telangana",  
"Chityala, Telangana",  
"Dameracherla, Telangana",  
"Devarakonda, Telangana",  
"Gundlapally (Dindi), Telangana",  
"Gurrampode, Telangana",  
"Kanagal, Telangana",  
"Kattangoor, Telangana",  
"Kethe Pally, Telangana",  
"Konda Mallepally, Telangana",  
"Madugulapally, Telangana",  
"Marriguda, Telangana",  
"Miryalaguda, Telangana",  
"Munugode, Telangana",  
"Nakrekal, Telangana",  
"Nalgonda, Telangana",  
"Nampally, Telangana",  
"Narketpally, Telangana",  
"Neredugommu, Telangana",  
"Nidamanoor, Telangana",  
"Pedda Adiserlapally, Telangana",  
"Peddavoora, Telangana",  
"Shali Gouraram, Telangana",  
"Thipparthi, Telangana",  
"Tirumalagiri Sagar, Telangana",  
"Tripuraram, Telangana",  
"Vemula Pally, Telangana",  

"Narayanpet, Telangana",  
"Damaragidda, Telangana",  
"Dhanwada, Telangana",  
"Kosgi, Telangana",  
"Krishna, Telangana",  
"Maddur, Telangana",  
"Maganoor, Telangana",  
"Makthal, Telangana",  
"Marikal, Telangana",  
"Narayanpet, Telangana",  
"Narva, Telangana",  
"Utkoor, Telangana",  

"Nirmal, Telangana",  
"Basar, Telangana",  
"Bhainsa, Telangana",  
"Dasturabad, Telangana",  
"Dilawarpur, Telangana",  
"Kaddam (Peddur), Telangana",  
"Khanapur, Telangana",  
"Kubeer, Telangana",  
"Kuntala, Telangana",  
"Laxmanchanda, Telangana",  
"Lokeswaram, Telangana",  
"Mamda, Telangana",  
"Mudhole, Telangana",  
"Narsapur G, Telangana",  
"Nirmal, Telangana",  
"Nirmal Rural, Telangana",  
"Pembi, Telangana",  
"Sarangapur, Telangana",  
"Soan, Telangana",  
"Tanur, Telangana",  

"Nizamabad, Telangana",  
"Armur, Telangana",  
"Balkonda, Telangana",  
"Bheemgal, Telangana",  
"Bodhan, Telangana",  
"Chandur, Telangana",  
"Dharpalle, Telangana",  
"Dichpalle, Telangana",  
"Indalwai, Telangana",  
"Jakranpalle, Telangana",  
"Kammarapalle, Telangana",  
"Kotgiri, Telangana",  
"Makloor, Telangana",  
"Mendora, Telangana",  
"Mortad, Telangana",  
"Mosara, Telangana",  
"Mugpal, Telangana",  
"Mupkal, Telangana",  
"Nandipet, Telangana",  
"Navipet, Telangana",  
"Nizamabad North, Telangana",  
"Nizamabad Rural, Telangana",  
"Nizamabad South, Telangana",  
"Renjal, Telangana",  
"Rudrur, Telangana",  
"Sirkonda, Telangana",  
"Varni, Telangana",  
"Velpur, Telangana",  
"Yedapalle, Telangana",  
"Yergatla, Telangana",  

"Peddapalli, Telangana",  
"Anthergaon, Telangana",  
"Dharmaram, Telangana",  
"Eligaid, Telangana",  
"Julapalli, Telangana",  
"Kamanpur, Telangana",  
"Manthani, Telangana",  
"Mutharam (Manthani), Telangana",  
"Odela, Telangana",  
"Palakurthy, Telangana",  
"Peddapalli, Telangana",  
"Ramagiri, Telangana",  
"Ramagundam, Telangana",  
"Srirampur, Telangana",  
"Sulthanabad, Telangana",  

"Rajanna Sircilla, Telangana",  
"Boinpalli, Telangana",  
"Chandurthi, Telangana",  
"Ellanthakunta, Telangana",  
"Gambhiraopet, Telangana",  
"Konaraopet, Telangana",  
"Mustabad, Telangana",  
"Rudrangi, Telangana",  
"Sircilla, Telangana",  
"Thangallapalli, Telangana",  
"Veernapalli, Telangana",  
"Vemulawada, Telangana",  
"Vemulawada Rural, Telangana",  
"Yellareddipet, Telangana",  

"Wanaparthy, Telangana",  
"Amarchintha, Telangana",  
"Amarachintha, Telangana",  
"Atmakur, Telangana",  
"Chinnambavi, Telangana",  
"Ghanpur, Telangana",  
"Gopalpeta, Telangana",  
"Kothakota, Telangana",  
"Madanapur, Telangana",  
"Pangal, Telangana",  
"Pebbair, Telangana",  
"Peddamandadi, Telangana",  
"Revally, Telangana",  
"Srirangapur, Telangana",  
"Wanaparthy, Telangana",  
"Weepangandla, Telangana",  

"Warangal, Telangana",  
"Chennaraopet, Telangana",  
"Duggondi, Telangana",  
"Geesugonda, Telangana",  
"Khanapur, Telangana",  
"Khila Warangal, Telangana",  
"Nalla Belli, Telangana",  
"Nallabelli, Telangana",  
"Narsampet, Telangana",  
"Nekkonda, Telangana",  
"Parvathagiri, Telangana",  
"Raiparthy, Telangana",  
"Rayaparthy, Telangana",  
"Sangem, Telangana",  
"Warangal, Telangana",  
"Wardhanna Pet, Telangana",  
"Wardhannapet, Telangana",  

"Yadadri Bhuvanagiri, Telangana",  
"Adda Guduru, Telangana",  
"Addaguduru, Telangana",  
"Alair, Telangana",  
"Atmakur (M), Telangana",  
"Atmakur(M), Telangana",  
"B Pochampally, Telangana",  
"B.Pochampally, Telangana",  
"Bhongir, Telangana",  
"Bibinagar, Telangana",  
"Bommalaramaram, Telangana",  
"Bommala Ramaram, Telangana",  
"Choutuppal, Telangana",  
"Gundala, Telangana",  
"Motakonduru, Telangana",  
"Mothkur, Telangana",  
"Narayanpur, Telangana",  
"Narayanapur, Telangana",  
"Rajapeta, Telangana",  
"Rajapet, Telangana",  
"Ramannapet, Telangana",  
"Ramannapeta, Telangana",  
"Thurkapally, Telangana",  
"Valigonda, Telangana",  
"Yadagirigutta, Telangana",  

"Ranga Reddy, Telangana",  
"Abdullapurmet, Telangana",  
"Amangal, Telangana",  
"Balapur, Telangana",  
"Chevella, Telangana",  
"Farooqnagar, Telangana",  
"Gandipet, Telangana",  
"Hayathnagar, Telangana",  
"Ibrahimpatnam, Telangana",  
"Jilled Chowdergudem, Telangana",  
"Kadthal, Telangana",  
"Kandukur, Telangana",  
"Keshampeta, Telangana",  
"Kondurg, Telangana",  
"Kothur, Telangana",  
"Madgul, Telangana",  
"Maheshwaram, Telangana",  
"Manchal, Telangana",  
"Moinabad, Telangana",  
"Nandigama, Telangana",  
"Rajendranagar, Telangana",  
"Saroornagar, Telangana",  
"Serilingampally, Telangana",  
"Shabad, Telangana",  
"Shamshabad, Telangana",  
"Shankarpally, Telangana",  
"Talakondapalle, Telangana",  
"Yacharam, Telangana",  

"Sangareddy, Telangana",  
"Ameenpur, Telangana",  
"Andole, Telangana",  
"Chowtakur, Telangana",  
"Gummadidala, Telangana",  
"Hathnoora, Telangana",  
"Jharasangam, Telangana",  
"Jinnaram, Telangana",  
"Kalher, Telangana",  
"Kandi, Telangana",  
"Kangti, Telangana",  
"Kohir, Telangana",  
"Kondapur, Telangana",  
"Manoor, Telangana",  
"Mogudampally, Telangana",  
"Munipally, Telangana",  
"Nagalgidda, Telangana",  
"Narayankhed, Telangana",  
"Nyalkal, Telangana",  
"Patancheru, Telangana",  
"Pulkal, Telangana",  
"Raikode, Telangana",  
"Ramchandrapuram, Telangana",  
"Sadasivpet, Telangana",  
"Sangareddy, Telangana",  
"Sirgapoor, Telangana",  
"Vatpally, Telangana",  
"Zahirabad, Telangana",  

"Siddipet, Telangana",  
"Akkannapet, Telangana",  
"Bejjanki, Telangana",  
"Cheriyal, Telangana",  
"Chinnakodur, Telangana",  
"Dhoolmitta, Telangana",  
"Doultabad, Telangana",  
"Dubbak, Telangana",  
"Gajwel, Telangana",  
"Husnabad, Telangana",  
"Jagdevpur, Telangana",  
"Koheda, Telangana",  
"Komuravelli, Telangana",  
"Kondapak, Telangana",  
"Maddur, Telangana",  
"Markook, Telangana",  
"Mirdoddi, Telangana",  
"Mulug, Telangana",  
"Nanganoor, Telangana",  
"Narayanaraopet, Telangana",  
"Raipole, Telangana",  
"Siddipet Rural, Telangana",  
"Siddipet Urban, Telangana",  
"Thoguta, Telangana",  
"Wargal, Telangana",  

"Suryapet, Telangana",  
"Ananthagiri, Telangana",  
"Atmakur (S), Telangana",  
"Chilkur, Telangana",  
"Chinthalapalem Mallareddygudem, Telangana",  
"Chivvemla, Telangana",  
"Garide Pally, Telangana",  
"Huzurnagar, Telangana",  
"Jaji Reddi Gudem (Arvapally), Telangana",  
"Kodad, Telangana",  
"Maddirala, Telangana",  
"Mattam Pally, Telangana",  
"Mella Chervu, Telangana",  
"Mothey, Telangana",  
"Munagala, Telangana",  
"Nadigudem, Telangana",  
"Nagaram, Telangana",  
"Nereducherla, Telangana",  
"Nuthankal, Telangana",  
"Palakeedu, Telangana",  
"Penpahad, Telangana",  
"Suryapet, Telangana",  
"Thirumalagiri, Telangana",  
"Thungathurthi, Telangana",  
"Thungaturthy, Telangana",  

"Vikarabad, Telangana",  
"Bantwaram, Telangana",  
"Basheerabad, Telangana",  
"Bomaraspeta, Telangana",  
"Bomraspeta, Telangana",  
"Chowdapur, Telangana",  
"Dharur, Telangana",  
"Doma, Telangana",  
"Doulathabad, Telangana",  
"Doulatabad, Telangana",  
"Kodangal, Telangana",  
"Kotepally, Telangana",  
"Kulkacharla, Telangana",  
"Marpalle, Telangana",  
"Marpally, Telangana",  
"Mominpet, Telangana",  
"Nawabpet, Telangana",  
"Pargi, Telangana",  
"Peddemul, Telangana",  
"Pudur, Telangana",  
"Tandur, Telangana",  
"Vikarabad, Telangana",  
"Yelal, Telangana",  
"Yalal, Telangana",  

"A. C. Guards, Hyderabad",  
"A. S. Rao Nagar, Hyderabad",  
"Abhyudaya Nagar, Hyderabad",  
"Abids, Hyderabad",  
"Adibatla, Hyderabad",  
"Adikmet, Hyderabad",  
"Afzal Gunj, Hyderabad",  
"Aghapura, Hyderabad",  
"Aliabad, Hyderabad",  
"Alijah Kotla, Hyderabad",  
"Allwyn Colony, Hyderabad",  
"Alwal, Hyderabad",  
"Amberpet, Hyderabad",  
"Ameenpur, Hyderabad",  
"Ameerpet, Hyderabad",  
"Anandbagh, Hyderabad",  
"Ashok Nagar, Hyderabad",  
"Asif Nagar, Hyderabad",  
"Attapur, Hyderabad",  
"Azamabad, Hyderabad",  
"Azampura, Hyderabad",  
"Badichowdi, Hyderabad",  
"Bagh Lingampally, Hyderabad",  
"Bairamalguda, Hyderabad",  
"Balapur, Hyderabad",  
"Balkampet, Hyderabad",  
"Banjara Hills, Hyderabad",  
"Bank Street, Hyderabad",  
"Barkas, Hyderabad",  
"Barkatpura, Hyderabad",  
"Basheerbagh, Hyderabad",  
"Bazarghat, Hyderabad",  
"Begum Bazaar, Hyderabad",  
"Begumpet, Hyderabad",  
"Bharat Nagar, Hyderabad",  
"BHEL Township, Hyderabad",  
"Boggulkunta, Hyderabad",  
"Bolarum, Hyderabad",  
"Borabanda, Hyderabad",  
"Bowenpally, Hyderabad",  
"Chaderghat, Hyderabad",  
"Chaitanyapuri, Hyderabad",  
"Chandanagar, Hyderabad",  
"Chandrayangutta, Hyderabad",  
"Chappal Bazar, Hyderabad",  
"Charminar, Hyderabad",  
"Chawani, Hyderabad",  
"Chengicherla, Hyderabad",  
"Cherlapally, Hyderabad",  
"Chikkadpally, Hyderabad",  
"Chilkanagar, Hyderabad",  
"Chintal, Hyderabad",  
"Chintalbasti, Hyderabad",  
"Chintalkunta, Hyderabad",  
"Chitrapuri Colony, Hyderabad",  
"Chowmahalla, Hyderabad",  
"Chudi Bazaar, Hyderabad",  
"Dabeerpura, Hyderabad",  
"Dammaiguda, Hyderabad",  
"Dattatreya Colony, Hyderabad",  
"Dilsukhnagar, Hyderabad",  
"Domalguda, Hyderabad",  
"Doodhbowli, Hyderabad",  
"Durganagar, Hyderabad",  
"Dwarakapuri, Hyderabad",  
"ECIL, Hyderabad",  
"Erragadda, Hyderabad",  
"Erram Manzil, Hyderabad",  
"Esamia Bazaar, Hyderabad",  
"Falaknuma, Hyderabad",  
"Fateh Maidan, Hyderabad",  
"Fatehnagar, Hyderabad",  
"Film Nagar, Hyderabad",  
"Gachibowli, Hyderabad",  
"Gaddiannaram, Hyderabad",  
"Gagan Mahal, Hyderabad",  
"Gajularamaram, Hyderabad",  
"Gandhinagar, Hyderabad",  
"Ghatkesar, Hyderabad",  
"Golconda, Hyderabad",  
"Gosha Mahal, Hyderabad",  
"Gowliguda, Hyderabad",  
"Gowlipura, Hyderabad",  
"Gudimalkapur, Hyderabad",  
"Gulzar Houz, Hyderabad",  
"Gunfoundry, Hyderabad",  
"Habshiguda, Hyderabad",  
"Hafeezpet, Hyderabad",  
"Habsiguda, Hyderabad",  
"Hakimpet, Hyderabad",  
"Hanuman Tekdi, Hyderabad",  
"Hasan Nagar, Hyderabad",  
"Hastinapuram, Hyderabad",  
"Hayathnagar, Hyderabad",  
"Himayatnagar, Hyderabad",  
"Hitec City, Hyderabad",  
"Huda Colony, Hyderabad",  
"Humayun Nagar, Hyderabad",  
"Ibrahim Bagh, Hyderabad",  
"Ibrahimpatnam, Hyderabad",  
"IDPL Colony, Hyderabad",  
"Indira Nagar, Hyderabad",  
"Indira Park, Hyderabad",  
"International Airport, Hyderabad",  
"Ismailkhanguda, Hyderabad",  
"Jafferguda, Hyderabad",  
"Jahanuma, Hyderabad",  
"Jalpally, Hyderabad",  
"Jam Bagh, Hyderabad",  
"Jambagh, Hyderabad",  
"Jawahar Nagar, Hyderabad",  
"Jeedimetla, Hyderabad",  
"Jillelaguda, Hyderabad",  
"Jubilee Hills, Hyderabad",  
"Kachiguda, Hyderabad",  
"Kakatiya Nagar, Hyderabad",  
"Kalasiguda, Hyderabad",  
"Kalyan Nagar, Hyderabad",  
"Kanchanbagh, Hyderabad",  
"Kapra, Hyderabad",  
"Karwan, Hyderabad",  
"Kavadiguda, Hyderabad",  
"Keesara, Hyderabad",  
"Khanamet, Hyderabad",  
"Khairatabad, Hyderabad",  
"Kismatpur, Hyderabad",  
"Kompally, Hyderabad",  
"Kondapur, Hyderabad",  
"Kothapet, Hyderabad",  
"Koti, Hyderabad",  
"Kukatpally, Hyderabad",  
"Kulsumpura, Hyderabad",  
"Kushaiguda, Hyderabad",  
"Kukatpally Housing Board Colony (KPHB), Hyderabad",  
"L. B. Nagar, Hyderabad",  
"Lad Bazaar, Hyderabad",  
"Lakdikapul, Hyderabad",  
"Lal Darwaza, Hyderabad",  
"Lallaguda, Hyderabad",  
"Langar Houz, Hyderabad",  
"Laxmi Nagar, Hyderabad",  
"Lothkunta, Hyderabad",  
"Madhapur, Hyderabad",  
"Madhura Nagar, Hyderabad",  
"Malkajgiri, Hyderabad",  
"Mallepally, Hyderabad",  
"Malakpet, Hyderabad",  
"Manikonda, Hyderabad",  
"Marredpally, Hyderabad",  
"Masab Tank, Hyderabad",  
"Mehdipatnam, Hyderabad",  
"Mettuguda, Hyderabad",  
"Miyapur, Hyderabad",  
"Moazzam Jahi Market, Hyderabad",  
"Moghalpura, Hyderabad",  
"Moula Ali, Hyderabad",  
"Moti Nagar, Hyderabad",  
"Moula-ka-Chilla, Hyderabad",  
"Musheerabad, Hyderabad",  
"Mushirabad, Hyderabad",  
"Mylardevpally, Hyderabad",  
"Nacharam, Hyderabad",  
"Nagaram, Hyderabad",  
"Nagarjuna Nagar, Hyderabad",  
"Nallakunta, Hyderabad",  
"Nampally, Hyderabad",  
"Nanakramguda, Hyderabad",  
"Narsingi, Hyderabad",  
"Nayapul, Hyderabad",  
"Necklace Road, Hyderabad",  
"New Bhoiguda, Hyderabad",  
"New Malakpet, Hyderabad",  
"Nizampet, Hyderabad",  
"NTR Nagar, Hyderabad",  
"Old Bowenpally, Hyderabad",  
"Old City, Hyderabad",  
"Old Malakpet, Hyderabad",  
"Osman Nagar, Hyderabad",  
"Osman Sagar, Hyderabad",  
"Osmanabad, Hyderabad",  
"Osmania University, Hyderabad",  
"Padmarao Nagar, Hyderabad",  
"Panjagutta, Hyderabad",  
"Patancheru, Hyderabad",  
"Patencheru, Hyderabad",  
"Peddamberpet, Hyderabad",  
"Peerancheru, Hyderabad",  
"Phisal Banda, Hyderabad",  
"Pragathi Nagar, Hyderabad",  
"Puppalaguda, Hyderabad",  
"Purana Pul, Hyderabad",  
"Quthbullapur, Hyderabad",  
"Qutub Shahi Tombs, Hyderabad",  
"Raidurg, Hyderabad",  
"Raj Bhavan, Hyderabad",  
"Rajendranagar, Hyderabad",  
"Ramanthapur, Hyderabad",  
"Ramgopalpet, Hyderabad",  
"S. R. Nagar, Hyderabad",  
"Safilguda, Hyderabad",  
"Saidabad, Hyderabad",  
"Saifabad, Hyderabad",  
"Sainikpuri, Hyderabad",  
"Sanathnagar, Hyderabad",  
"Sanghi Nagar, Hyderabad",  
"Santoshnagar, Hyderabad",  
"Saroornagar, Hyderabad",  
"Secunderabad, Hyderabad",  
"Serilingampally, Hyderabad",  
"Shah-Ali-Banda, Hyderabad",  
"Shahran Market, Hyderabad",  
"Shanker Mutt, Hyderabad",  
"Shivam Road, Hyderabad",  
"Sikh Village, Hyderabad",  
"Silpa Avenue Colony, Hyderabad",  
"Sindhi Colony, Hyderabad",  
"Sitaphal Mandi, Hyderabad",  
"Somajiguda, Hyderabad",  
"South Banjara Hills, Hyderabad",  
"Sri Nagar Colony, Hyderabad",  
"Sultan Bazaar, Hyderabad",  
"Sultan Shahi, Hyderabad",  
"Suraram, Hyderabad",  
"Swaraj Nagar, Hyderabad",  
"Tadbun, Hyderabad",  
"Tarnaka, Hyderabad",  
"Tellapur, Hyderabad",  
"Toli Chowki, Hyderabad",  
"Trimulgherry, Hyderabad",  
"Tukkuguda, Hyderabad",  
"Tulasinagar, Hyderabad",  
"Turkayamjal, Hyderabad",  
"Uppal, Hyderabad",  
"Upparpally, Hyderabad",  
"Ursu, Hyderabad",  
"Vanasthalipuram, Hyderabad",  
"Vengal Rao Nagar, Hyderabad",  
"Venkatapuram, Hyderabad",  
"Vidyanagar, Hyderabad",  
"Vijay Nagar Colony, Hyderabad",  
"Vikarabad, Hyderabad",  
"Vinayak Nagar, Hyderabad",  
"Vishnupuri, Hyderabad",  
"Warasiguda, Hyderabad",  
"West Marredpally, Hyderabad",  
"Yadagirigutta, Hyderabad",  
"Yakutpura, Hyderabad",  
"Yapral, Hyderabad",  
"Yellareddyguda, Hyderabad",  
"Yousufguda, Hyderabad",  
"Zahirabad, Hyderabad",  
"Zamistanpur, Hyderabad",
  ],
  Tripura: ["Agartala, Tripura", "Udaipur, Tripura", "Kailashahar, Tripura"],
  "Uttar Pradesh": [
    "Noida, Uttar Pradesh",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
  ],
  Uttarakhand: [
    "Dehradun, Uttarakhand",
    "Haridwar, Uttarakhand",
    "Nainital, Uttarakhand",
  ],
  "West Bengal": [
    "Kolkata, West Bengal",
    "Darjeeling, West Bengal",
    "Siliguri, West Bengal",
  ],

  // USA major cities locations
  Arizona: [
    "Phoenix, Arizona",
    "Tucson, Arizona",
    "Mesa, Arizona",
    "Scottsdale, Arizona",
    "Chandler, Arizona",
  ],
  California: [
    "Los Angeles, California",
    "San Francisco, California",
    "San Diego, California",
    "Sacramento, California",
    "San Jose, California",
  ],
  Florida: [
    "Miami, Florida",
    "Orlando, Florida",
    "Tampa, Florida",
    "Jacksonville, Florida",
    "St. Petersburg, Florida",
  ],
  Illinois: [
    "Chicago, Illinois",
    "Aurora, Illinois",
    "Naperville, Illinois",
    "Springfield, Illinois",
    "Rockford, Illinois",
  ],
  "New York": [
    "New York City, New York",
    "Buffalo, New York",
    "Rochester, New York",
    "Albany, New York",
    "Syracuse, New York",
  ],
  "North Carolina": [
    "Charlotte, North Carolina",
    "Raleigh, North Carolina",
    "Greensboro, North Carolina",
    "Durham, North Carolina",
    "Winston-Salem, North Carolina",
  ],
  Ohio: [
    "Columbus, Ohio",
    "Cleveland, Ohio",
    "Cincinnati, Ohio",
    "Toledo, Ohio",
    "Akron, Ohio",
  ],
  Pennsylvania: [
    "Philadelphia, Pennsylvania",
    "Pittsburgh, Pennsylvania",
    "Allentown, Pennsylvania",
    "Harrisburg, Pennsylvania",
    "Erie, Pennsylvania",
  ],
  Texas: [
    "Houston, Texas",
    "Dallas, Texas",
    "Austin, Texas",
    "San Antonio, Texas",
    "Fort Worth, Texas",
  ],
  remote:["Remote"]
};